name: publish

on:
  push:
    branches:
      - release

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.changelog.outputs.tag }}
      skipped: ${{ steps.changelog.outputs.skipped }}
      changelog: ${{ steps.changelog.outputs.changelog }}
      version: ${{ steps.changelog.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GIT_TOKEN }}
      
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - run: |
          yarn init -y
          yarn add conventional-changelog-conventionalcommits@7.0.2 --dev --frozen-lockfile
          yarn add conventional-recommended-bump@9.0.0 --dev --frozen-lockfile
      
      - name: Generate Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5.2.1
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          git-user-name: 'MangaYouKnow Bot'
          git-user-email: 'admin@myk.com'
          config-file-path: ./.github/.config.cjs
          pre-commit: ./.github/.pre-commit.cjs
          version-file: './MangaYouKnowDesktop/src-tauri/tauri.conf.json'
          skip-version-file: false
          skip-git-pull: false
          pre-release: true
      
      - run: |
          rm -rf node_modules
          rm package.json
  release:
    name: Release
    needs: changelog
    if: ${{ needs.changelog.outputs.skipped != 'true' }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GIT_TOKEN }}
          
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.7.1
      
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      
      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt update && sudo apt install -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            webkit2gtk-driver \
            xvfb
      
      - name: Install front-end dependencies
        run: pnpm install
        working-directory: ./MangaYouKnowDesktop
        
      - name: Update Cargo.toml
        run: bash library u ${{ needs.changelog.outputs.version }}
      
      - name: Publish Release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ needs.changelog.outputs.tag }}
          releaseBody: ${{ needs.changelog.outputs.changelog }}
          releaseDraft: true
          args: ${{ matrix.args }}
          projectPath: './MangaYouKnowDesktop'